title: Baseline Updates
email: r@rixx.de
description: >-
  Updates to the Baseline collection. Including RSS feeds (both for all updates and individual tags).
baseurl: "/baseline-updates"
url: "https://rixx.github.io"

# Build settings
plugins:
  - jekyll-feed

feed:
  tags: true
  posts_limit: 25
