title: Baseline Updates
email: r@rixx.de
description: >-
  Updates to the Baseline collection. Including RSS feeds (both for all updates and individual tags).
baseurl: "/baseline-updates"
url: "https://rixx.github.io/baseline-updates/"

# Build settings
plugins:
  - jekyll-feed

feed:
  tags: true
