name: Update blog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

premissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: baseline-updates
      - uses: actions/checkout@v4
        with:
          repository: web-platform-dx/web-features
          path: web-features
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
      - name: Install requirements
        run: python -m pip install ./bin/requirements.txt
      - name: Run update script
        run: python ./baseline-updates/bin/update.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: New baseline information
          repository: baseline-updates
